### ISSUE TITLE
Sliders default values geven

### ISSUE THREAD

**Issue by DriesVuylsteke** [wout97/wout97.github.io#2]
Eenmaal dat #1 werken kunnen we via de selected songs de informatie voor elk liedje apart makkelijk opvragen via: https://developer.spotify.com/documentation/web-api/reference/tracks/get-several-audio-features/

Deze features kunnen we dan het gemiddelde van berekenen en als default value voor de sliders instellen.

Belangrijk is dat wanneer we naar een eerder scherm gaan en de selected songs niet aanpassen (dus gewoon onnodig van scherm veraneren gelijk de geniale end user dat we zijn), dat de sliders hun aangepaste waarde aanhouden.

Eventueel zelfs de aangepaste waarde altijd bijhouden en een knop maken om de data te refreshen gebaseerd op de geselecteerde nummers?

**Comment by wout97** [comment]
Default waardes worden gegeven op basis van de seeds. Dus mss nieuwe issue maken dat we alle liedjes moeten gebruiken.
